# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=1.0
group=com.devnemo.nemos.quartz
java_version=21

# Common
minecraft_version=1.21.10
mod_name=Nemo's Quartz
mod_author=Nemo
mod_id=nemos_quartz
mod_id_jar=nemos-quartz
license=MIT
credits=Nemo
description=Add more quartz blocks to Minecraft!
minecraft_version_range=[1.21.10]
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.10-20251010.172816
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.10
parchment_version=2025.10.12

# Fabric
fabric_version=0.138.3+1.21.10
fabric_loader_version=0.18.1

# Forge
forge_version=60.1.0
forge_loader_version_range=[60,)

# NeoForge
neoforge_version=21.10.53-beta
neoforge_loader_version_range=[10,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Dependencies

# Upload
curseforge_project_id=1389652
modrinth_project_id=nemos-quartz